export default [{
    title: '首页',
    icon: 'desktop',
    href: '/home'
}, {
    title: '基础布局',
    icon: 'home',
    children: [{
        title: '布局',
        href: '/layout'
    }, {
        title: '图标和按钮',
        href: '/button'
    }]
}, {
    title: '数据展示',
    icon: 'area-chart',
    children: [{
        title: '表格',
        href: '/table'
    }, {
        title: '树形',
        href: '/tree'
    }, {
        title: '分页',
        href: '/page'
    }, {
        title: '标签和标记',
        href: '/badge'
    }]
}, {
    title: '表单',
    icon: 'desktop',
    children: [{
        title: '单选与多选',
        href: '/radio'
    }, {
        title: '输入框',
        href: '/input'
    }, {
        title: '日历',
        href: '/date'
    }, {
        title: '表单验证',
        href: '/validate'
    }, {
        title: '动态表单',
        href: '/dynamic'
    }]
}, {
    title: '导航',
    icon: 'bars',
    children: [{
        title: '导航菜单',
        href: '/nav'
    }, {
        title: '标签',
        href: '/tabs'
    }, {
        title: '下拉菜单',
        href: '/dropdown'
    }, {
        title: '步骤条',
        href: 'steps'
    }]
}, {
    title: '消息通知',
    icon: 'cubes',
    href: '/notice'
}, {
    title: '弹框',
    icon: 'calendar',
    children: [{
        title: '对话框',
        href: '/dialog'
    }, {
        title: '折叠面板',
        href: '/collapse'
    }, {
        title: '轮播图',
        href: '/carousel'
    }]
},]
